name: Main
on:
  push:
    tags:
      - '*'
jobs:
  Build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Publish
      uses: jerray/publish-docker-action@v1.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: jerray/golang
        auto_tag: true
